### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by allenvpn312** [alejandro-du/paged-tabs#13]
Hi Alejandro,

Is there a way to size the tabs evenly when the width is less than the horizontal viewport?  If not, would be cool to have a ThemeVariant to do so, similar to other Vaadin components such as Button and such.

Thanks.

**Comment by alejandro-du** [comment]
I think this would be a feature request for the `vaadin-tabs` component. Maybe it's currently possible with CSS, though.
