### ISSUE TITLE
component not visible in second tab

### ISSUE THREAD

**Issue by nnani** [alejandro-du/paged-tabs#19]
I am using ApexCharts library to get charts component objects.
Somehow the first Table shows the component, while second table does not show at all.

When checked in Dev console, it shows the component property hidden=true.

Sample code :

VerticalLayout container = new VerticalLayout();
        PagedTabs tabs = new PagedTabs(container);
        Tab tab1 = tabs.add("Tab caption 1", LineChartExample(), false);
        Tab tab2 = tabs.add("Tab caption 2", LineChartExample(), false);
        add(tabs, container);

public ApexCharts LineChartExample() {
        ApexCharts lineChart = ApexChartsBuilder.get()
                .withChart(ChartBuilder.get()
                        .withType(Type.line)
                        .withZoom(ZoomBuilder.get()
                                .withEnabled(false)
                                .build())
                        .build())
                .withStroke(StrokeBuilder.get()
                        .withCurve(Curve.straight)
                        .build())
                .withTitle(TitleSubtitleBuilder.get()
                        .withText("Product Trends by Month")
                        .withAlign(Align.left)
                        .build())
                .withGrid(GridBuilder.get()
                        .withRow(RowBuilder.get()
                                .withColors("#f3f3f3", "transparent")
                                .withOpacity(0.5).build()
                        ).build())
                .withXaxis(XAxisBuilder.get()
                        .withCategories("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep")
                        .build())
                .withSeries(new Series<>("Desktops", 10.0, 41.0, 35.0, 51.0, 49.0, 62.0, 69.0, 91.0, 148.0))
                .build();
        return lineChart;
    }

If I try to encapsulate this chart object  in a Vertical Layout and add that object to Tabs it works, but the second tab is not scrollable and the size of object is small compared to first tab.

**Comment by alejandro-du** [comment]
I'm not able to reproduce using only the code you provide. If you can include a minimal running application, I'll reopen this and investigate the problem.
