### ISSUE TITLE
Do you have any plan for setting orientation feature?

### ISSUE THREAD

**Issue by ugurdoksan** [alejandro-du/paged-tabs#3]
Thanks for version 1.1.1. Do you have any plan to add orientation selection feature like in the original Tabs component? 

`
tabs.setOrientation( Tabs.Orientation.VERTICAL ); 
tabs.setOrientation( Tabs.Orientation.HORIZONTAL);
`

**Comment by alejandro-du** [comment]
You can get the underlying `Tabs` component and configure anything you want:

```
var pagedTabs = new PagedTabs(container);
Tabs tabs = pagedTabs.getContent();
```
