### ISSUE TITLE
Possibility to make wrapper scrollable

### ISSUE THREAD

**Issue by Juchar** [alejandro-du/paged-tabs#4]
It would be nice to be able to specify if the page content should be shrinked to the wrapper or if the wrapper will show a scrollbar instead.

This can be achieved by using `getElement().getStyle().set("overflow", "auto");` on the `VerticalLayout wrapper = new VerticalLayout(component);`.

**Comment by alejandro-du** [comment]
The current implementation decouples the page container from the `PagedTabs` component, so I think it should be possible since you control the "viewport" now.
