### ISSUE TITLE
Tab Select Programmatically has side affect

### ISSUE THREAD

**Issue by ugurdoksan** [alejandro-du/paged-tabs#5]
### INFO-1
_I am using PagedTabs in a dialog with save button has three tabs._
_Before save action, I validate all of the tabs._
_If any of tabs is invalid, I select the first invalid tab programmatically (**pagedTabs.select(xTab)**);_

**There is not any problem until here...**

### INFO-2
_After the selection of invalid tabs, I select another valid tab from UI with mouse. And the problem occurs._
_The invalid tabs selected programmatically is added the valid tabs bottom!_

_Note: When I select the invalid tab again from UI with mouse, UI becomes normal._

### CODE
My code is simple and there is nothing can produce this problem. My code is below:

`
public class OrderDialog{

        private VerticalLayout vl;
	private PagedTabs pagedTabs;

	private Tab				tabOrderInfo;
	private OrderInfoPanel	orderInfoPanel;

	private Tab				tabOrderItems;
	private OrderItemsPanel	orderItemsPanel;

       public OrderDialog(){

		 setWidth( "600px" );
                 vl = new VerticalLayout();
                 add(vl);

		pagedTabs = new PagedTabs( );
		pagedTabs.setWidth( "570px" );
		vl.add( pagedTabs );

		tabOrderInfo = new Tab( "Sipariş Bilgisi" );
		orderInfoPanel = new OrderInfoPanel( bean );
		pagedTabs.add( orderInfoPanel, tabOrderInfo );

		tabOrderItems = new Tab( "Sipariş Edilen Ürünler" );
		orderItemsPanel = new OrderItemsPanel( bean );
		pagedTabs.add( orderItemsPanel, tabOrderItems );

		Button btn = new Button();
                vl.add(btn);
                btn.addClickListener( e->{
                  
                if( !orderInfoPanel.isValid( ) ) {
                   pagedTabs.select( tabOrderInfo );
                   return;
                }
		OrderService.getInstance( ).save( bean );
               });
	
              open( );
	}
}
`

**Comment by ugurdoksan** [comment]
If it is necessary I can share the codes about panels... But I think the problem is about content mechanism of PagedTabs

**Comment by alejandro-du** [comment]
Are you able to share a [reduced test case](https://vaadin.com/blog/5-tips-to-get-your-issue-solved-quicker-in-open-source-projects#4_provide_a_reduced_test_case) so I can reproduce the issue?

**Comment by ugurdoksan** [comment]
I've simplified the code above :) I think it is enough to reproduce the problem.

**Comment by alejandro-du** [comment]
Thanks but can you provide a reduced test case that I can actually compile?

**Comment by ugurdoksan** [comment]
Hi @alejandro-du .

Here is the test case you can actually compile:

```
public class ProductDialog extends Dialog {

	private VerticalLayout	vl;
	private PagedTabs		pagedTabs;

	private Tab			firstTab;
	private FirstPanel	firstPanel;

	private Tab			secondTab;
	private SecondPanel	secondPanel;

	public ProductDialog( ) {

		setWidth( "600px" );
		vl = new VerticalLayout( );
		add( vl );

		pagedTabs = new PagedTabs( );
		pagedTabs.setWidth( "570px" );
		vl.add( pagedTabs );

		firstTab = new Tab( "First" );
		firstPanel = new FirstPanel( );
		pagedTabs.add( firstPanel, firstTab );

		secondTab = new Tab( "Second" );
		secondPanel = new SecondPanel( );
		pagedTabs.add( secondPanel, secondTab );

		addButtonBar( );
		open( );
	}

	private void addButtonBar( ){

		Button btnCancel = new Button( "Cancel" );
		btnCancel.addClickListener( e -> close( ) );
		btnCancel.setWidth( "50%" );

		Button btnSave = new Button( "Save" );
		btnSave.addClickListener( e -> onCreateOrUpdate( ) );
		btnSave.setWidth( "50%" );

		HorizontalLayout hl = new HorizontalLayout( btnCancel, btnSave );
		hl.setWidth( "100%" );
		vl.add( hl );
	}

	private boolean onCreateOrUpdate( ){

		if( !firstPanel.isValid( ) ) {
			pagedTabs.select( firstTab );
			return false;
		}
		if( !secondPanel.isValid( ) ) {
			pagedTabs.select( secondTab );
			return false;
		}

		return true;
	}

	class FirstPanel extends VerticalLayout {

		public FirstPanel( ) {

			setSizeFull( );
			add( new Label( "First Panel" ) );
		}

		public boolean isValid( ){

			return true;
		}
	}

	class SecondPanel extends VerticalLayout {

		public SecondPanel( ) {

			setSizeFull( );
			add( new Label( "Second Panel" ) );
		}

		public boolean isValid( ){

			return false;// To see the bug
		}
	}
}

```

**Comment by ugurdoksan** [comment]
@alejandro-du 

Here is the scenario images you can use to reproduce the bug:

![1](https://user-images.githubusercontent.com/24225109/54480056-2dc71880-4835-11e9-92a6-5535213e5876.PNG)

![2](https://user-images.githubusercontent.com/24225109/54480059-315a9f80-4835-11e9-9ba4-1f60d800f74b.PNG)

![3](https://user-images.githubusercontent.com/24225109/54480062-33bcf980-4835-11e9-816d-36ffa0b6ff94.PNG)

**Comment by ugurdoksan** [comment]
**The Scenario:**

**1 ->** Click the '_Save Button_'.
**2 ->** The '_Second Panel_' is selected **programmatically**.
**3 ->** Select the '_First Panel_' **manually**.

**Result:**
'_First Panel_' with '_First Panel Label_' is **OK**.
But the _label of 'Second Panel'_ appears after _the label of 'First Panel'_ is the **Bug**.

**Comment by alejandro-du** [comment]
Thanks for the example. I found a bug in the `select(Tab)` method when used with Vaadin 12 or later. I just fixed it and upgraded to Vaadin 13. Please check with the latest version of the component  (1.2.0) and let me know if the issue persists.

**Comment by ugurdoksan** [comment]
@alejandro-du The problem is solved. Thanks :)

**Comment by alejandro-du** [comment]
Great! Thanks for reporting the issue.

**Comment by allenvpn312** [comment]
Since PagedTabs allow adding other components in addition to Tab, can you also add a select(int tabIndex) for cases where components are not wrapped inside a Tab?

Thanks.
