### ISSUE TITLE
2.0.0 Version Is Not Working With Vaadin 14.0.2

### ISSUE THREAD

**Issue by ugurdoksan** [alejandro-du/paged-tabs#7]
**Vaadin Version:** 14.0.2
**Paged Tabs Version:** 2.0.0
**Application Server:** Tomcat
**Browser:** Any Browser with latest version

Tomcat Error SS is below:

![TomcatErrorMessage](https://user-images.githubusercontent.com/24225109/63871875-60209880-c9c5-11e9-8356-89b16d3c270b.PNG)

**Comment by realulim** [comment]
I can reproduce this with Vaadin 14.0.0 as well.
